import Versions.tinkoffDotsIndicator

object ProjectDependencies {
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val kotlinCoroutineCore =
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlin_coroutine}"
    const val kotlinCoroutineAndroid =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlin_coroutine}"
    const val kotlin_work = "androidx.work:work-runtime-ktx:${Versions.kotlin_work}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:${Versions.fragmentKtx}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.constrantLayout}"
    const val material = "com.google.android.material:material:${Versions.design}"
    const val recyclerview = "androidx.recyclerview:recyclerview:${Versions.recyclerview}"
    const val lifecycleCommon = "androidx.lifecycle:lifecycle-common-java8:${Versions.lifecycle}"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val lifecycleKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    const val lifecycleExtensionKtx = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycleExt}"
    const val lifecycleLiveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycle}"
    const val collectionKtx = "androidx.collection:collection-ktx:${Versions.collectionKtx}"
    const val lifecycle = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle}"

    const val lifecycleReactivestreams =
        "androidx.lifecycle:lifecycle-reactivestreams:${Versions.lifecycle}"
    const val lottie = "com.airbnb.android:lottie:${Versions.lottie}"
    const val transition = "androidx.transition:transition:${Versions.transition}"

    const val photoView = "com.github.chrisbanes:PhotoView:${Versions.photoView}"
    const val htextviewScale = "com.hanks:htextview-scale:${Versions.htextView}"
    const val htextviewBase = "com.hanks:htextview-base:${Versions.htextView}"
    const val shadowLayout = "com.github.lihangleo2:ShadowLayout:${Versions.shadowLayout}"
    const val whatIf = "com.github.skydoves:whatif:${Versions.whatIf}"

    const val flexbox = "com.google.android:flexbox:${Versions.flexbox}"
    const val recyclerview_anim = "jp.wasabeef:recyclerview-animators:${Versions.recyclerview_anim}"
    const val room = "androidx.room:room-runtime:${Versions.room}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.room}"
    const val roomRx = "androidx.room:room-rxjava2:${Versions.room}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val moshiRetrofit = "com.squareup.retrofit2:converter-moshi:${Versions.moshiRetrofit}"
    const val moshiKotlin = "com.squareup.moshi:moshi-kotlin:${Versions.moshiKotlin}"
    const val googleMaps = "com.google.android.gms:play-services-maps:${Versions.googleMaps}"
    const val facebookSdk = "com.facebook.android:facebook-core:${Versions.facebookSdk}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val okhttp_logger = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val tensorFlow = "org.tensorflow:tensorflow-lite:${Versions.tensorFlow}"
    const val generex = "com.github.mifmif:generex:${Versions.generex}"
    const val diskCache = "com.jakewharton:disklrucache:${Versions.diskCache}"
    const val junit = "junit:junit:${Versions.jUnit}"
    const val junitExt = "androidx.test.ext:junit:${Versions.junitExt}"
    const val mockito = "org.mockito:mockito-core:${Versions.mockito}"
    const val truth = "com.google.truth:truth:${Versions.truth}"
    const val json = "org.json:json:${Versions.json}"
    const val appUpdate = "com.google.android.play:app-update:${Versions.appUpdate}"
    const val appUpdateKtx = "com.google.android.play:app-update-ktx:${Versions.appUpdate}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glideProccessor = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val coil = "io.coil-kt:coil:${Versions.coil}"
    const val okhttpLogger = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val chucker = "com.github.chuckerteam.chucker:library:${Versions.chucker}"
    const val chuckerNoOp = "com.github.chuckerteam.chucker:library-no-op:${Versions.chucker}"
    const val multidex = "com.android.support:multidex:${Versions.multidex}"
    const val zxing = "com.google.zxing:core:${Versions.zxing}"
    const val zxingAndroid = "com.journeyapps:zxing-android-embedded:${Versions.zxingAndroid}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val rollingText = "com.github.YvesCheung:RollingText:${Versions.rollingText}"
    const val photoCompressor = "id.zelory:compressor:${Versions.photoCompressor}"
    const val circleindicator = "me.relex:circleindicator:${Versions.circleIndicator}"
    const val fab = "uk.co.markormesher:android-fab:${Versions.fab}"
    const val playCore = "com.google.android.play:core:${Versions.playCore}"
    const val playService = "com.google.android.gms:play-services-auth:${Versions.playService}"
    const val playAuthApi = "com.google.android.gms:play-services-auth-api-phone:${Versions.playAuthApi}"
    const val swiperLayout = "com.chauthai.swipereveallayout:swipe-reveal-layout:${Versions.swipeLayout}"
    const val rootbeer = "com.scottyab:rootbeer-lib:${Versions.rootbeer}"
    const val commonsLang = "org.apache.commons:commons-lang3:${Versions.commonsLang}"
    const val commonsCollections =
        "org.apache.commons:commons-collections4:${Versions.commonsCollections}"
    const val commonsIO = "commons-io:commons-io:${Versions.commonsIO}"
    const val smartcards = "net.sf.scuba:scuba-smartcards:${Versions.smartcards}"
    const val viewpager2 = "androidx.viewpager2:viewpager2:${Versions.viewpager2}"
    const val glideOkHttpIntegration =
        "com.github.bumptech.glide:okhttp3-integration:${Versions.glideOkhhtpIntegration}"
    const val playServicesVision =
        "com.google.android.gms:play-services-vision:${Versions.playServicesVision}"
    const val playServicesVisionCommon =
        "com.google.android.gms:play-services-vision-common:${Versions.playServicesVisionCommon}"
    const val findBugs = "com.google.code.findbugs:jsr305:${Versions.findBugs}"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val desugar = "com.android.tools:desugar_jdk_libs:${Versions.desugar}"
    const val threetenabp = "com.jakewharton.threetenabp:threetenabp:${Versions.threetenabp}"
    const val asynclayoutinflater =
        "androidx.asynclayoutinflater:asynclayoutinflater:${Versions.asynclayoutinflater}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val permissionsdispatcher =
        "com.github.permissions-dispatcher:permissionsdispatcher:${Versions.permissionsdispatcher}"
    const val permissionsdispatcherProcessor =
        "com.github.permissions-dispatcher:permissionsdispatcher-processor:${Versions.permissionsdispatcher}"
    const val tinkOffDotsIndicator =
        "ru.tinkoff.scrollingpagerindicator:scrollingpagerindicator:${tinkoffDotsIndicator}"
    const val navigationComponent =
        "androidx.navigation:navigation-fragment:${Versions.navigationComponent}"
    const val navigationUiKtx =
        "androidx.navigation:navigation-ui:${Versions.navigationComponent}"
    const val supportDesign = "com.android.support:design:${Versions.supportDesign}"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    const val koinCore = "org.koin:koin-core:${Versions.koin}"
    const val koinAndroid = "io.insert-koin:koin-android:${Versions.koin}"
    const val pawegio = "com.pawegio.kandroid:kandroid:${Versions.pawegio}"
    const val kotPref = "com.chibatching.kotpref:kotpref:${Versions.kotPref}"
    const val kotPrefGsonSupport = "com.chibatching.kotpref:gson-support:${Versions.kotPref}"
    const val kotPrefEnum = "com.chibatching.kotpref:enum-support:${Versions.kotprefEnum}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    const val rxKotlin = "io.reactivex.rxjava2:rxkotlin:${Versions.rxKotlin}"
    const val anko = "org.jetbrains.anko:anko:${Versions.anko}"
    const val groupie = "com.xwray:groupie:${Versions.groupie}"
    const val groupieExtension = "com.xwray:groupie-kotlin-android-extensions:${Versions.groupie}"
    const val legacySupport = "androidx.legacy:legacy-support-v4:${Versions.legacy_support}"
    const val vision = "com.google.firebase:firebase-ml-vision"
    const val firebaseAnalyticsNoVersion = "com.google.firebase:firebase-analytics-ktx"
    const val firebaseCrashlyticsNoVersion = "com.google.firebase:firebase-crashlytics-ktx"
    const val firebaseMessagingNoVersion = "com.google.firebase:firebase-messaging-ktx"
    const val firebaseFirestoreNoVersion = "com.google.firebase:firebase-firestore-ktx"
    const val firebaseRemoteConfigNoVersion = "com.google.firebase:firebase-config-ktx"
    const val firebaseStoreNoVersion = "com.google.firebase:firebase-storage-ktx"
    const val firebaseBom = "com.google.firebase:firebase-bom:${Versions.firebaseBom}"
    const val firebaseFirestore = "com.google.firebase:firebase-firestore-ktx"
    const val firebaseFunctions = "com.google.firebase:firebase-functions-ktx"
    const val firebaseStorage = "com.google.firebase:firebase-storage:${Versions.firebaseStorage}"
    const val firebaseStorageKtx = "com.google.firebase:firebase-storage-ktx:${Versions.firebaseStorage}"
    const val firebaseAuth = "com.google.firebase:firebase-auth-ktx:${Versions.firebaseAuth}"
    const val firebaseDynamicLinks =
        "com.google.firebase:firebase-dynamic-links-ktx:${Versions.firebaseDynamicLinks}"
    const val kotlinCoroutinePlayServices =
        "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.kotlin_coroutine}"
    const val facebookLogin = "com.facebook.android:facebook-login:${Versions.facebook}"
    const val circleImage = "de.hdodenhof:circleimageview:${Versions.circleImage}"
    const val droopy = "com.shehabic.droppy:Droppy:${Versions.droopy}"
    const val stfalcon = "com.github.stfalcon:stfalcon-imageviewer:${Versions.stfalcon}"
    const val easyprefs = "com.pixplicity.easyprefs:library:${Versions.easyprefs}"
    const val dToast = "com.github.Dovar66:DToast:${Versions.dToast}"
    const val stripe = "com.stripe:stripe-android:${Versions.stripe}"
    const val permissionDispatcher =
        "com.github.permissions-dispatcher:permissionsdispatcher:${Versions.permissionDispatcher}"
    const val permissionDispatcherProcessor =
        "com.github.permissions-dispatcher:permissionsdispatcher-processor:${Versions.permissionDispatcher}"
    const val pagingLibrary = "androidx.paging:paging-runtime-ktx:${Versions.pagingVersion}"
    const val pagingCommonLibrary = "androidx.paging:paging-common:${Versions.pagingVersion}"
    const val crashReportingLib = "ch.acra:acra-mail:${Versions.acraVersion}"
    const val crashReportingCore = "ch.acra:acra-core:${Versions.acraVersion}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltKapt = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val splashScreen = "androidx.core:core-splashscreen:${Versions.splashScreen}"
    const val paging = "androidx.paging:paging-runtime:${Versions.paging}"
    const val facebook = "com.facebook.android:facebook-android-sdk:${Versions.facebookVersion}"
    const val tagTargetView = "com.getkeepsafe.taptargetview:taptargetview:${Versions.tagTargetView}"
    const val dotsIndicator = "com.tbuonomo:dotsindicator:${Versions.dotsIndicator}"
    const val customBottomNavigation = "com.gauravk.bubblenavigation:bubblenavigation:${Versions.customBottomNavigation}"
    const val yandexMetrics = "com.yandex.android:mobmetricalib:${Versions.yandexMetrics}"
    const val workManager = "androidx.work:work-runtime-ktx:${Versions.workManager}"
    const val guava = "com.google.guava:guava:${Versions.guava}"
    const val mlKitFaceDetection = "com.google.mlkit:face-detection:${Versions.mlKitFaceDetection}"
    const val camera2 = "androidx.camera:camera-camera2:${Versions.cameraX}"
    const val cameraLifecycle = "androidx.camera:camera-lifecycle:${Versions.cameraX}"
    const val cameraView = "androidx.camera:camera-view:${Versions.cameraX}"
    const val cameraCore = "androidx.camera:camera-core:${Versions.cameraX}"
    const val onDeviceML = "com.google.android.odml:image:${Versions.onDeviceML}"
    const val activityKtx = "androidx.activity:activity-ktx:${Versions.activityKtx}"
    const val serenegiantCommon = "com.serenegiant:common:${Versions.serenegiantCommon}"
    const val lifecycleService = "androidx.lifecycle:lifecycle-service:${Versions.lifecycleService}"
}
